config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :logs 

  

end

app/views/shared/_flashes.html.erb
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!--  Testing dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-clients" data-toggle="dropdown">Testing</span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Tests plan" ,class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Test cases", class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Logs",logs_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          </ul>
        </div>
      </div>

      <!--  Managing dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="avatar dropdown-toggle navbar-wagon-item navbar-wagon-link" id="navbar-wagon-menu-clients" data-toggle="dropdown">Managing</span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "Planning" ,class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Resources" ,class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Budget", class: "navbar-wagon-item navbar-wagon-link" %></li>
            <li><%= link_to "Delivrables", class: "navbar-wagon-item navbar-wagon-link" %></li>
          </ul>
        </div>
      </div>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Profile</a></li>
            <li><a href="#">Dashboard</a></li>
            <li><%= link_to "Log out", destroy_user_session_path,method: :delete,class: "navbar-wagon-item navbar-wagon-link" %></li>
          </ul>
        </div>
      </div>

    <% else %>

      <%= link_to "Sign in", new_user_session_path,class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign up", new_user_registration_path,class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>



  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>