config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :logs 

  

end

app/models/log.rb
# == Schema Information
#
# Table name: logs
#
#  id                     :integer          not null, primary key
#  code                   :string
#  label                  :string
#  description            :text
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  log_stage_id           :integer
#  log_status_id          :integer
#  log_type_id            :integer
#  log_added_value_id     :integer
#  expectation            :text
#  creator_id             :integer
#  owner_id               :integer
#  expected_milestone_id  :integer
#  confirmed_milestone_id :integer
#
# Indexes
#
#  index_logs_on_log_added_value_id  (log_added_value_id)
#  index_logs_on_log_stage_id        (log_stage_id)
#  index_logs_on_log_status_id       (log_status_id)
#  index_logs_on_log_type_id         (log_type_id)
#
# Foreign Keys
#
#  fk_rails_5d8142ca38  (log_added_value_id => log_added_values.id)
#  fk_rails_a7b0e10252  (log_stage_id => log_stages.id)
#  fk_rails_d4bbae0d68  (log_type_id => log_types.id)
#  fk_rails_e8a3b31969  (log_status_id => log_statuses.id)
#

class Log < ApplicationRecord



#############################################################################
# log parameters
#############################################################################

@code_max_length = 7
@code_min_length = 6
@label_max_length = 40
@description_min_length = 10


#############################################################################
# Data  model relationships
#############################################################################

  belongs_to :log_stage
  belongs_to :log_status
  belongs_to :log_added_value
  belongs_to :log_type
  belongs_to :expected_milestone, class_name: 'Milestone'
  belongs_to :confirmed_milestone, class_name: 'Milestone'
  belongs_to :creator, class_name: 'User'
  belongs_to :owner, class_name: 'User'

  # Destroy is used in order to ensure when the log is deleted then 
  # the comments related with are also deleted 
  has_many :comments, dependent: :destroy

  

#############################################################################
# Log business rules and validation
#############################################################################


##################### Business rules #######################################

  # BR-LOGS-001 : If controls are valid then generate the code according the
  # following statement
  # Then the code is generated if the code is not already created or the log type
  # has been changed
  # code = log_type.code + random number between 1 and 9999
  # the random number has to be in format NNNN (4 digits)
  # IE : CR0001


  before_validation :set_code , if: :log_type?


  # BR-LOGS-002 : Generating CSV file for log export

  def self.to_csv
    attributes = %w{code label description code_type label_type code_status label_status}
    CSV.generate(headers:true) do |csv|
      csv << attributes
      all.each do |log|
        csv << [log.code, log.label,log.description,log.log_type.code, log.log_type.label,
         log.log_status.code,log.log_status.label ]
      end
    end
  end









####################### validation ##########################################

######## Validation on log type

  # CTRL-LOGS-007 : The log type is mandatory
  validates :log_type, presence: {presence: true, message: "CTRL-LOGS-007 : The log type is mandatory "}

######## Validation on log status

  # CTRL-LOGS-008 : The log status is mandatory
  validates :log_status, presence: {presence: true, message: "CTRL-LOGS-008 : The log status is mandatory "}

######## Validation on log code

  # CTRL-LOGS-001 : The code is mandatory
  validates :code, presence: {presence: true, message: "CTRL-LOGS-001 : The code is mandatory"}

  # CTRL-LOGS-002 : The code is unique
  validates :code, uniqueness: {uniqueness: true, message: "CTRL-LOGS-002 : Code already existing, the code must be unique"}

  # CTRL-LOGS-003 : The code length can not exceed the max length
  validates :code, length: {maximum: @code_max_length, message: "CTRL-LOGS-003 : The code length can not exceed #{@code_max_length} caracters" }

  # CTRL-LOGS-004 : The code length can not below the minimum length
  validates :code, length: {minimum: @code_min_length, message: "CTRL-LOGS-004 : The code length can not be below #{@code_min_length} caracters" }


######## Validation on log label

  # CTRL-LOGS-005 : The title is mandatory
  validates :label, presence: {presence: true, message: "CTRL-LOGS-005 : The log title can not be blank "}

  # CTRL-LOGS-006 : The title can not execeed max length
  validates :label, length: {maximum: @label_max_length, message: "CTRL-LOGS-006 : The code length can not exceed #{@label_max_length} caracters" }






######## Validation on log description

  # CTRL-LOGS-009 : The description is mandatory
  validates :description, length: {minimum: @description_min_length, message: "CTRL-LOGS-008 : The description length can not be below #{@description_min_length} caracters" }


######## After saving log 

  # CTRL-LOGS-010 : The description is mandatory

  after_save :send_mail_to_creator

private


  def set_code
    if self.code == nil or log_type.code[0..1] != self.code[0..1]
      temp_code = generate_code(self.log_type.code)
      while Log.exists?(code: temp_code)
        temp_code = generate_code
      end
      self.code = temp_code
    end
  end


  def generate_code(log_type_code)
    code = ""
    code = log_type_code + rand(9999).to_s.rjust(4,'0')
  end

  def log_type? 
    self.log_type != nil 
  end 


  def send_mail_to_creator

    UserMailer.log_notification_email(self.creator).deliver_now

  end 





end

#############################################################################
# End of file
#############################################################################

app/models/log_type.rb
# == Schema Information
#
# Table name: log_types
#
#  id          :integer          not null, primary key
#  code        :string
#  label       :string
#  description :text
#  active      :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class LogType < ApplicationRecord

#############################################################################
# Data  model relationships
#############################################################################
  has_many :logs


#############################################################################
# Scope on set data`
#############################################################################

  # Scope on the active item
  scope :active, -> {
    where(active: true)
  }


end

app/controllers/logs_controller.rb
class LogsController < ApplicationController


  before_action :find_log, only: [:show,:edit,:update, :destroy]
  before_action :find_log_status_open, only: [:new,:create]
  before_action :find_log_status, only: [:index,:show,:edit,:update]
  before_action :find_log_added_value, only: [:index,:new,:create,:show,:edit,:update]
  before_action :find_log_stage, only: [:index,:new,:create,:show,:edit,:update]
  before_action :find_log_type, only: [:index,:new,:create,:show,:edit,:update]
  before_action :find_milestone, only: [:index,:new,:create,:show,:edit,:update]
  
  
  def index

    @search = Log.search(params[:q])
    @logs = @search.result.includes(:log_stage,:log_status,:log_type,:log_added_value,:creator,:owner,:expected_milestone,:confirmed_milestone)

    respond_to do |format|
      format.html
      format.csv {send_data @logs.to_csv, filename: "Logs Selection-#{Date.today}.csv"}
      format.js
    end

  end


  def show
  end


  def new
    @log = Log.new
    #respond_to do |format|
        #format.html
        #format.js
    #end
  end


  def create
    @log = Log.new(log_params)
    @log.creator = current_user
    if @log.save
      redirect_to logs_path
    else
      render :new
    end
  end


  def edit
    
  end


  def update
    #@comments = @log.comments
    @log.owner = current_user
    if @log.update(log_params)
      redirect_to logs_path
    else
      render :edit
    end
  end

  # CTRL-LOGS-0xx: Only the user is allowed to delete an existing
  # if the user wanting to delete the log is not the owner then trigger blocking error

  def destroy
    if is_owner?
      @log.destroy
      respond_to do |format|
        format.html {redirect_to logs_path}
        format.js
      end
    else
      redirect_to logs_path, flash: { alert: "CTRL-LOGS-0xx: You are not the owner of the current log it can not be deleted by you" }
    end
  end

  private

  # Avoid paramters hacking
  def log_params
    params.require(:log).permit(:code,:label,:description,:log_added_value_id,
      :log_stage_id,:log_status_id,:log_type_id,:expectation,
      :creator_id,:owner_id,:expected_milestone_id,:confirmed_milestone_id)
  end



  def find_log
    @log = Log.find(params[:id])
  end

  # Following methods are used to
  # gather objects related to log object

  def find_log_status
    @selectable_status = LogStatus.active
  end


  def find_log_status_open
    @selectable_status = LogStatus.open
  end


  def find_log_added_value
    @selectable_values = LogAddedValue.active
  end


  def find_log_stage
    @selectable_stages = LogStage.active
  end


  def find_log_type
    @selectable_types = LogType.active
  end


  def find_milestone
    @selectable_milestones = Milestone.active
  end

  def is_owner?
    @log.creator.id == current_user.id
  end


end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/_log_form.html.erb
<!-- Middle of the work area for the log form page (Creation and Update)-->
<!-- Displaying the detail view of log-->


<%= simple_form_for @log do |l| %>
  
  <!--Display of the error list -->
  <%= render "log_form_errors_list" %>
  
  <!-- Div managing the log entry -->
  <div class="form-middle-component-area-height">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" role="tablist">
      <li role="presentation" class="active">
        <a href="#log-home" aria-controls="log-home" role="tab" data-toggle="tab">
          <i class="fa fa-th-list" aria-hidden="true"> Description</i>
        </a>
      </li>
      <li role="presentation">
        <a href="#log-comments" aria-controls="log-comments" role="tab" data-toggle="tab">
          <i class="fa fa-commenting" aria-hidden="true"> Comments</i>
        </a>
      </li>
      <li role="presentation">
        <a href="#log-attachements" aria-controls="log-attachements" role="tab" data-toggle="tab">
        <i class="fa fa-paperclip" aria-hidden="true"> Attachements</i>
        </a>
      </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">

      <!-- Home tab of the log form --> 
      <%= render partial: "log_form_tab_home",object: @log,:locals => {l: l} %>

      <!-- Comments tab of the log form -->
      <%= render partial: "log_form_tab_comments",object: @log, :locals => {l: l} %>
    
      <!-- Attachements tab of the log form -->
      <%= render partial: "log_form_tab_attachements",object: @log, :locals => {l: l} %>
   
    </div>

  </div>

  <!-- Buttons area -->
  <%= render partial: "log_form_buttons",object: @log, :locals => {l: l} %>
  
<% end %>

app/views/logs/_log_form_buttons.html.erb
<!-- Buttons area -->
<div class="work-area-features-height work-area-features marging-top">
  <div class="form-inline">
    <div class="form-group spacing-search">
      <%= l.button :submit, "Validate", class: "btn btn-success button-features" %>
    </div>
    <div class="form-group spacing-search">
      <%= link_to logs_path do %>
        <button type="button" name="Back" class="btn btn-primary button-features">Back</button>
      <% end %>
    </div>
  </div>
</div>

app/views/logs/_log_form_tab_attachements.html.erb
<!-- Attachements tab of the log form --> 
<div role="tabpanel" class="tab-pane fade marging-top" id="log-attachements" >
  Tab 3
</div>

app/views/logs/_log_form_tab_comments.html.erb
<!-- Comments tab of the log form --> 
<div role="tabpanel" class="tab-pane fade marging-top" id="log-comments" >
	<div>
  		<!-- Left panel of the middle area -->
	  	<div class="left-small element-inline component-area-height padding-right " >
	  	</div>

  		<!-- Right panel of the middle area -->
	  	<div class="right-large element-inline component-area-height padding-right">
	  	</div> 
	</div>
</div>

app/views/logs/_log_form_tab_home.html.erb
<div role="tabpanel" class="tab-pane fade in active marging-top" id="log-home">
  <div>

  <!-- Left panel of the middle area -->
  <div class="left-small element-inline component-area-height padding-right " >

    <div>
      <div class="element-inline input-margin-right">
        <%= l.association :log_type, label:'Type',collection: @selectable_types, readonly: true, error: false , include_blank: true, label_method: lambda { |log_type| "#{log_type.code} - #{log_type.label}" },input_html: {class: 'medium-field'} %>
      </div>
      <div class="element-inline input-margin-right">
        <%= l.association :log_status, label:'Status', collection: @selectable_status, readonly: true, error: false ,include_blank: false, label_method: lambda { |log_status| "#{log_status.code} - #{log_status.label}" },input_html: {class: 'medium-field'} %>
      </div>
    </div>

    <div>
      <div class="element-inline input-margin-right">
        <%= l.input :code, label:"Code",readonly: true , error: false ,input_html: {class: 'small-field', maxlength: 7 }%>
      </div>
      <div class="element-inline input-margin-right">
        <%= l.input :label, label:"Title", error: false ,input_html: {class: 'large-field', maxlength: 40 } %>
      </div>
    </div>

    <div>
      <div class="element-inline input-margin-right">
        <%= l.association :log_stage, label:'Insertion stage', collection: @selectable_stages, readonly: true, include_blank: true, label_method: lambda { |log_stage| "#{log_stage.label}" }, input_html: {class: 'medium-field'} %>
      </div>
      <div class="element-inline input-margin-right">
        <%= l.association :log_added_value, label:'Expected added value',collection: @selectable_values,readonly: true, :label_method => lambda { |log_added_value| "#{log_added_value.code} - #{log_added_value.label}" },include_blank: true,input_html: { class: 'medium-field' } %>
      </div>

    </div>

    <div>
      <div class="element-inline input-margin-right">
        <label for="log-cby">Created by</label>
        <% if @log.creator != nil %>
          <p class="form-control medium-field" id="log-cby" readonly><%= @log.creator.alias %></p>
        <% else %>
         <p class="form-control medium-field" id="log-cby" readonly>Not yet created</p>
        <% end %>
      </div>
      <div class="element-inline input-margin-right">
        <label for="log-uby">Updated by</label>
        <% if @log.owner != nil %>
          <p class="form-control medium-field" id="log-uby" readonly><%= @log.owner.alias %> </p>
        <% else %>
          <p class="form-control medium-field" id="log-uby" readonly>No owner</p>
        <% end %>
      </div>
    </div>

    <div>
      <div class="element-inline input-margin-right">
        <%= l.association :expected_milestone, label:'Expected milestone',collection: @selectable_milestones,readonly: true, :label_method => lambda { |milestone| "#{milestone.code} - #{milestone.label}" },include_blank: true,input_html: { class: 'medium-field' } %>
      </div>
      <div class="element-inline input-margin-right">
        <%= l.association :confirmed_milestone, label:'Confirmed milestone',collection: @selectable_milestones,readonly: true, :label_method => lambda { |milestone| "#{milestone.code} - #{milestone.label}" },include_blank: true,input_html: { class: 'medium-field' } %>
      </div>
    </div>

    <div>
      <div class="element-inline input-margin-right">
        <label for="log-doc">Date of creation</label>
        <p class="form-control medium-field" id="log-doc" readonly> <%= @log.created_at %> </p>
      </div>
      <div class="element-inline input-margin-right">
        <label for="log-dou">Date of update</label>
        <p class="form-control medium-field" id="log-dou" readonly> <%= @log.updated_at %> </p>
      </div>
    </div>
  </div>

  <!-- Right panel of the middle area -->
  <div class="right-large element-inline component-area-height padding-right">
    <div>
      <div class="element-inline element-margin-right">
        <%= l.input :description, label:"Current status",error: false,input_html: {class: 'input-for-resume' , rows: 8}%>
      </div>
    </div>
    <div>
      <div class="element-inline element-margin-right">
        <%= l.input :expectation, label:"Expectation", input_html: {class: 'input-for-resume', rows: 8}%>
      </div>
    </div>
  </div> 
  </div>
</div>

app/views/logs/_logs-list-features.html.erb
<div class="form-inline">

  <!-- Feature to create a new log -->
  <div class="form-group spacing-search">
    <%= link_to new_log_path do %>
      <button type="button" name="New" class="btn btn-primary button-features">New</button>
    <% end %>
  </div>

  <!-- Feature to export the logs  -->
  <div class="form-group spacing-search">
    <%= link_to logs_path(format: "csv") do %>
      <button type="button" name="LogCSV" class="btn btn-default button-features">Export</button>
    <% end %>
  </div>

</div>

app/views/logs/_logs-list.html.erb
<% if @logs.length == 0 %>
  <!--Message is displayed if the list is empty -->
  <%= render "components/no-result-found" %>
<% else %>
  <table id="log-table" class="table table-striped table-area">
    <!-- Table Header -->
    <tr>
      <th></th>
      <th>Code</th>
      <th>Title</th>
      <th>Type</th>
      <th>Stage</th>
      <th>Confirmed milestone</th>
      <th>Value</th>
      <th>Status</th>
      <th>Created by</th>
    </tr>
    <!-- Table data -->
    <% @logs.each do |log| %>
    <tr>
      <td>
        <ul class="list-inline product-controls hidden-sm hidden-xs">
          <li>
            <%= link_to edit_log_path(log) do %>
              <i class="fa fa-pencil"> </i>
            <% end %>
          </li>
          <li>
            <%= link_to log_path(log), method: :delete do %>
              <i class="fa fa-trash"> </i>
            <% end %>
          </li>
        </ul>
      </td>
      <td><%= log.code  %></td>
      <td><%= log.label %></td>
      <td><%= log.log_type.label %></td>
      <td><%= log.log_stage.label %></td>
      <% if log.confirmed_milestone != nil %>
        <td><%= log.confirmed_milestone.label %> </td>
      <% else %>
       <td>Not confirmed</td>
      <% end %>
      <td><%= log.log_added_value.label %></td>
      <td><%= log.log_status.label %> </td >
      <td> <%= log.creator.alias %> </td>
    </tr>

    <% end %>
  </table>
<% end %>

app/views/logs/_logs-search.html.erb
<div class="search-height">
  <%= form_tag logs_path, class: "form-inline" , method: "get" do %>
    <%= render "search-param" %>
  <% end %>
</div>

app/views/logs/_logs_search.html.erb
<div class="search-height">
  <%= form_tag logs_path, class: "form-inline" , method: "get" do %>
    <%= render "logs_search_param" %>
  <% end %>
</div>

app/views/logs/_logs_search_param.html.erb
 <%= search_form_for @search do |f| %>

   <div class="form-group spacing-search">
     <%= f.label :code_or_label_cont, "Entry" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.text_field :code_or_label_cont %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Type" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_type_id_eq,options_from_collection_for_select(@selectable_types,"id","label"),include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Status" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_status_id_eq,options_from_collection_for_select(@selectable_status,"id","label"),include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Stage" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_stage_id_eq,options_from_collection_for_select(@selectable_stages,"id","label"), include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Due" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :expected_milestone_id_eq,options_from_collection_for_select(@selectable_milestones,"id","label"), include_blank: true %>
   </div>

   <div class="form-group spacing-search">
       <%= f.submit "Search",class: "btn btn-primary button-features" %>
   </div>

 <% end %>

app/views/logs/_search-param.html.erb
 <%= search_form_for @search do |f| %>

   <div class="form-group spacing-search">
     <%= f.label :code_or_label_cont, "Entry" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.text_field :code_or_label_cont %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Type" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_type_id_eq,options_from_collection_for_select(@selectable_types,"id","label"),include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Status" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_status_id_eq,options_from_collection_for_select(@selectable_status,"id","label"),include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Stage" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :log_stage_id_eq,options_from_collection_for_select(@selectable_stages,"id","label"), include_blank: true %>
   </div>
   <div class="form-group spacing-search">
      <%= f.label "Due" %>
   </div>
   <div class="form-group spacing-search">
      <%= f.select :expected_milestone_id_eq,options_from_collection_for_select(@selectable_milestones,"id","label"), include_blank: true %>
   </div>

   <div class="form-group spacing-search">
       <%= f.submit "Search",class: "btn btn-primary button-features" %>
   </div>

 <% end %>

app/views/logs/destroy.js.erb
$('#<%=@log.id%>').remove();

app/views/logs/new.js.erb
//$('#log-attachements').hide().after('<%= j render("log_form") %>')
//$('#log-comments').hide().after('<%= j render("log_form") %>');
//alert('coucou');

app/views/logs/update.html.erb
<div class="work-area">
  <div class="work-area-top work-area-components">
    <div class="work-area-top-title work-area-top-components">
      <h2>Log</h2>
    </div>
  </div>
  <div class="work-area-components">
    <%= render "log_form" %>
  </div>
</div>